[package]
name = "network-packet-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
pnet = "0.35.0"
tokio = { version = "1.40.0", features = ["full"] }
